global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.224.130:9090']  
  - job_name: 'devops-app'
    static_configs:
      - targets: ['192.168.224.130:9100'] 