version: '3.8'

services:
  frontend:
    image: tum3d/pi-appfront-image
    ports:
      - "8082:80"
    volumes:
      - uploads:/app/uploads
    networks:
      - spring-net

  backend:
    image: tum3d/pi-appback-image
    ports:
      - "9001:9000"
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: pi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 9000
    depends_on:
      - mysql
    networks:
      - spring-net

  mysql:
    image: mysql:8.0.36
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

volumes:
  uploads:
  mysql_data:

networks:
  spring-net:
